name: Hello world project

on: 
 push:
   branches:
     - main
     - develop
     - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: echo "Building the code"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the code after build
        run: echo "Testing the code with junit"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code in staging environment
        run: | 
          echo "Deploying the code for user acceptance"
          echo "Dale..."
  
