name: Hello world project

on: 
  push:
   branches:
     - main
     - develop
     - 'release/**'
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: |
          echo "Docker username is ${{ vars.DOCKER_USERNAME }}"
          echo "Docker password is ${{ secrets.Docker_Password }}"


  
