name: Hello world project

on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: Build Hello WOrld
       run: |
         echo "Hello WOrld...!!!"
         echo "Welcome to Nayak's world..."
