name: output demo for github actions
on: push
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Step one for output
        id: step12
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
      - name: step two to call the output
        run: echo "This version is ${{ steps.step12.outputs.version }}"
